fix(#1099): hexo server error when changing the config
hexojs/hexo pull request #5055
Opened 2022-09-09 04:38 UTC by D-Sketon

## What does it do?

fix(#1099): `hexo server` error when I change the config
when `new_post_name` lacks `:title`, `new_post_name` is used as the slug

## Screenshots

## Pull request tasks

- [ ] Add test cases for the changes.
- [x] Passed the CI test.

2022-09-09 06:22 UTC, renbaoshuo requested changes
Could you please add test cases for the changes?

2022-09-09 07:09 UTC, D-Sketon commented
> Could you please add test cases for the changes?

Ok

2022-09-09 07:31 UTC, D-Sketon commented
> Could you please add test cases for the changes?

New test cases have been added

2022-10-05 15:38 UTC, yoshinorin approved these changes
@D-Sketon 
LGTM. Thank you :)

2022-10-05 15:38 UTC, merged