refactor highlight: add filter event for code block rendering
hexojs/hexo pull request #5095
Opened 2022-11-05 06:47 UTC by stevenjoezhang

## What does it do?

Currently, there are 3 files relevant to code highlighting
```
lib/plugins/filter/before_post_render/backtick_code_block.js
lib/plugins/tag/code.js
lib/plugins/tag/include_code.js
```

Each file is hardcoded with support for highlight.js and prismjs, which would make it very difficult to support other code highlighting functions.

To make it more flexible, I propose a new highlight filter:

```js
hexo.extend.filter.register('highlight', ...)
```

With this filter, developers can use custom code highlighting functions to replace the built-in highlight.js or prismjs. 

Issue resolved: https://github.com/hexojs/hexo/issues/1891

## Screenshots

## Pull request tasks

- [ ] Add test cases for the changes.
- [x] Passed the CI test.

2022-11-05 06:52 UTC, renbaoshuo submitted a review, later dismissed
👍 LGTM

2022-11-05 06:53 UTC, stevenjoezhang commented
Discussion: should we use filter api to support `highlight` event, or create a new `hexo.extend.highlight` api? See https://github.com/hexojs/hexo/issues/4010#issuecomment-601182875

CC @hexojs/core

2022-11-05 07:09 UTC, renbaoshuo commented
I think we should use `hexo.extend.filter('highlight', ...)`. Because code highlighting is a (sometimes optional) step in the article rendering process.

2022-11-05 07:21 UTC, stevenjoezhang commented
Another difference is: other filters allow multiple callback functions to be registered per event, and callbacks are executed sequentially when the event is triggered. For code highlighting, only a single handler function should be registered. (For example, the user can choose either highlight.js or prism, but should not register both with `hexo.extend.filter`)

2022-11-05 07:21 UTC, SukkaW requested changes
IMHO, the ideal design is that we have a new plugin API `hexo.extend.highlight`.

## Register

```js
hexo.extend.highlight.register('highlight.js', highlighter);
hexo.extend.highlight.register('prismjs', highlighter);
hexo.extend.highlight.register('shiki', highlighter);
```

The `highlighter` should have an API interface like this:

```
declare function highlighter({
  code: string,
  language?: string,
  meta?: string,
  highlightLines?: unknown, // TBD
  lineNumbers?: boolean
}): string
```

2022-11-05 09:21 UTC, stevenjoezhang commented
New API interface of `highlighter`:
```ts
declare function highlighter(code: string, options: {
  language?: string,
  meta?: string,
  highlightLines?: unknown, // TBD
  lineNumbers?: boolean,
  // ...
}): string
```
The types of two parameters are the same as `require('hexo-util').highlight` and `require('hexo-util').prismHighlight`

Besides, can I remove the following code? It seems to be dead code
https://github.com/hexojs/hexo/blob/871ac4ff7046cbe443d3efb3d1a56abec4ae6486/lib/hexo/post.js#L409

2022-12-13 13:38 UTC, yoshinorin submitted a review, later dismissed
I suggested two comments, but basically LGTM. I think we can merge this.

2022-12-13 14:10 UTC, stevenjoezhang commented on lib/hexo/default_config.js
> +  highlighter: 'highlight.js',
That's right, I renamed this option because `highlighter` is similar to an existing `highlight` option and this may mislead users

2022-12-14 11:35 UTC, yoshinorin approved these changes
LGTM 🚀

2022-12-14 14:36 UTC, merged