compatible with hexo-abbrlink
hexojs/hexo pull request #5153
Opened 2023-02-02 14:57 UTC by KagamigawaMeguri

## What does it do?
When `post_asset_folder: true` and use [hexo-abbrlink](https://github.com/rozbo/hexo-abbrlink) plugin, image folder name where in `source/_posts` will be encoded into a string of numbers. 
Like: `testTitle` -> `28867439`.
It will break the image path so that images are not displayed correctly.

## Pull request tasks

- [x] Add test cases for the changes.
- [x] Passed the CI test.

2023-02-02 15:47 UTC, stevenjoezhang requested changes
Maybe you can consider modifying the hexo-abbrlink plugin instead?

2023-02-02 15:52 UTC, KagamigawaMeguri commented
> 

Others have consulted the hexo-abbrlink plugin developer, and he thinks it's hexo's problem.
Details in https://github.com/rozbo/hexo-abbrlink/issues/33

2023-02-06 14:30 UTC, yoshinorin commented
I'm not yet checking the behavior of `post_asset.js`. 

But I think maybe we can merge this. Because this PR passes all of the current tests. Also, it includes https://github.com/hexojs/hexo/pull/2881 for fixes #2134.

But we should change the PR title and source code comment. We should not change the source code for third-party plugins behavior.

2023-02-07 04:55 UTC, KagamigawaMeguri commented
> I'm not yet checking the behavior of `post_asset.js`.
> 
> But I think maybe we can merge this. Because this PR passes all of the current tests. Also, it includes #2881 for fixes #2134.
> 
> But we should change the PR title and source code comment. We should not change the source code for third-party plugins behavior.

Thank you for your patience and guidance! Please review again if my changes match your explanation.

2023-05-01 14:30 UTC, yoshinorin approved these changes
@KagamigawaMeguri 
Sorry for the late reply. 
LGTM, I'll merge this. Thank you :)

2023-05-01 14:30 UTC, merged

2023-09-24 06:45 UTC, D-Sketon commented
Is this a breaking change?
This PR doesn't pass the current tests.

2023-09-24 07:33 UTC, uiolee commented
It looks like this PR did not run check.

and I tested in my PC.

```bash
  1146 passing (16s)
  5 pending
  1 failing

  1) Hexo
       Models
         PostAsset
           path - virtual - when permalink contains .htm not in the end:

      AssertionError: expected '2023\09\24\bar\bar\foo.html' to deeply equal '2023\09\24\bar\.htm-foo\foo.html'
      + expected - actual

      -2023\09\24\bar\bar\foo.html
      +2023\09\24\bar\.htm-foo\foo.html

      at Context.<anonymous> (D:\git\hexo\test\scripts\models\post_asset.js:95:22)
```

2023-10-07 17:39 UTC, yoshinorin commented
@D-Sketon @uiolee 
Sorry, I made some misunderstandings. I think we should revert this PR.