fix: pass the language option for codeblock tag
hexojs/hexo pull request #5259
Opened 2023-07-29 14:02 UTC by xihale

## What does it do?

I will pass the language option when I use either of `highlight.js` or `prism.js` for codeblock tag!

## Pull request tasks

- [ ] Add test cases for the changes.
- [ ] Passed the CI test.

2023-07-30 10:57 UTC, SukkaW requested changes
Would you mind adding unit test cases toward your changes?

2023-07-30 11:03 UTC, xihale commented
> Would you mind adding unit test cases toward your changes?

but, I don't know what unit test I should add, can you help me?

2023-07-30 11:03 UTC, xihale commented
> Would you mind adding unit test cases toward your changes?

but, I don't know what unit test I should add, can you help me?

2023-07-30 12:21 UTC, xihale commented
I added a unit test to test my changes and find a inconspicuous bug then fixed it.

2023-08-05 06:29 UTC, StephenNeelDurai commented on lib/plugins/tag/code.js
> +    return `<pre><code${options.lang !== undefined ? ` class="language-${options.lang}"` : ''}>${escapeHTML(content)}</code></pre>`;
**Identical blocks of code found** on this line (125 and 140). I think you can create this line as separate variable and use it both places.

2023-10-25 01:40 UTC, StephenNeelDurai approved these changes

2024-03-02 12:42 UTC, closed without merging