feat(load_config): remove findConfigPath
hexojs/hexo pull request #5591
Opened 2024-12-22 09:49 UTC by stevenjoezhang

## What does it do?

I've noticed that Hexo supports searching for configuration files with different suffixes, such as `_config.txt` and `_config.json`. However, this check is very loose, meaning that `_config.backup` or `_config.yml.bak` are also considered valid configuration files. This feature can cause confusion and even security issues for users. Typically, users use `_config.yml` only, and in cases of custom usage, they can specify `hexo.config_path`. This suggests that there is little need for custom suffixes. Therefore, I recommend removing this feature in the pull request.

## Screenshots

## Pull request tasks

- [x] Add test cases for the changes.
- [x] Passed the CI test.

2024-12-23 01:24 UTC, SukkaW requested changes
I still prefer to choose `config.yml` or `config.json` automatically without specifying it. We might wanna make `findConfigPath` more strict though.

2024-12-24 06:43 UTC, stevenjoezhang commented
@SukkaW I've updated the code, and now the JSON suffix is also supported.

2024-12-24 10:21 UTC, SukkaW requested changes

2025-04-19 05:56 UTC, yoshinorin approved these changes
LGTM :heart:

2025-05-03 03:45 UTC, merged